# Generated by Django 4.2.7 on 2023-11-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comments_bid_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='owner',
        ),
    ]
